Make the Address type complete
mpizenberg/elm-cardano pull request #22
Opened 2023-11-12 22:23 UTC by mpizenberg

Improve the address type to represent all possible addresses in Cardano.

2023-11-13 10:30 UTC, keyan-m requested changes

2023-11-13 10:30 UTC, keyan-m commented on src/ElmCardano/Address.elm
> +    | Stake { networkId : NetworkId, stakeCredential : Credential }
This implies UTxOs can sit at stake addresses, which as far as I know is not the case.

I think `StakeCredential` should have its own `toBech32` encoder that takes the network ID as an argument.

2023-11-13 10:47 UTC, mpizenberg commented on src/ElmCardano/Address.elm
> +    | Stake { networkId : NetworkId, stakeCredential : Credential }
> This implies UTxOs can sit at stake addresses, which as far as I know is not the case.

Oh so if there cannot be utxos in stake addresses, how is the pledge done? (Sorry if my question is dumb I'm not familiar with this)

> I think StakeCredential should have its own toBech32 encoder that takes the network ID as an argument.

I'm not sure to follow. Do you mean the `StakeCredential` type, currently defined as follows:
```elm
type StakeCredential
    = InlineCredential Credential
    | PointerCredential { slotNumber : Int, transactionIndex : Int, certificateIndex : Int }
```
I mean, yeah we eventually want bech32 encoders, I just haven't come around adding them yet as they are only for human consumption and we are still trying to getting machine consumption part right.

2023-11-13 16:00 UTC, keyan-m commented on src/ElmCardano/Address.elm
> +    | Stake { networkId : NetworkId, stakeCredential : Credential }
> Oh so if there cannot be utxos in stake addresses, how is the pledge done?

I presume by pledge you mean staking. If so, that's the purpose of the staking part. As far as I know, if a staking part is registered to a staking pool, any UTxO sitting at _any_ address that its staking part is the same, will be counted for the rewards.

You might already know this, but I think an example that can paint the picture a bit nicely, is a dApp that constructs an address for its users, such that the payment part of the address is that of the script, while the staking part belongs to the user. This way, if the contract locks users' funds, users can still accrue their staking rewards while using the dApp.

> Do you mean the `StakeCredential` type

Yeah, but I agree I might've jumped ahead. For an `Address`, I think a `toString` function would be good (implicitly picking Base58 for Byron addresses and Bech32 for Shelley ones), and a dedicated `toBech32` for `StakeCredential`.

2023-11-13 19:43 UTC, mpizenberg commented on src/ElmCardano/Address.elm
> +    | Stake { networkId : NetworkId, stakeCredential : Credential }
> I presume by pledge you mean staking

I meant stake pool owner pledge, but just because I don't know how that works, contrary to regular stake delegation that I understand indeed.

> This implies UTxOs can sit at stake addresses, which as far as I know is not the case.

Ok I got another confirmation in txpipe discord that utxos live at byron or shelley addresses. And that Stake addresses (also called reward addresses) do not hold utxos. They are related to reward accounts for stake delegation and can be used for things related to staking and reward withdrawals. So it probably makes sense to only keep Byron | Shelley in that address type.

> For an Address, I think a toString function would be good

Agreed! Let's do this later. Or if you want to work on the algorithms, be my guest :)

2023-11-13 20:50 UTC, mpizenberg commented
Ok, I've done some changes with your feedback @keyan-m. I think this is better now.

2023-11-13 23:00 UTC, merged

2023-11-14 06:19 UTC, keyan-m commented on tests/ElmCardano/CoinSelectionTests.elm
> +    Bytes.fromStringUnchecked ("addr" ++ suffix)
This doesn't look right... Isn't `Bytes` meant to carry only hex formatted strings? Perhaps a good excuse to remove exposure of `fromStringUnchecked`!

2023-11-14 09:38 UTC, mpizenberg commented on tests/ElmCardano/CoinSelectionTests.elm
> +    Bytes.fromStringUnchecked ("addr" ++ suffix)
Yeah you're right, I think this was added just for readability of the test failure. The input needed utxo, so with an address part, but the algorithm doesn't care about the address part, so a dummy address was put in the test. I looked at it weird at first too, but then realized it doesn't matter for these tests, and is just convenient for readability of tests failure.

A better way would be to have the coin selection algorithm not rely on full utxos, and just what matters, the values, but then you have to re-attach the selected values to their corresponding utxos, with something, like an id, or an index or whatever. This just implies more complexity on user code so I don't think it's worth it.

Another fix would be to have a few valid addresses around, but really, it doesn't matter for this test and would just degrade readability of tests failure.

Regarding not exposing `fromStringUnchecked` it's a valid point. And I think at some point we want to hide it. I just don't think the API is mature/stable enough to know exactly how to workaround all the places that need building bytes yet. That will be revisited before publishing a first version on elm packages for sure.