[WIP] Basic Largest First Coin Selection
mpizenberg/elm-cardano pull request #5
Opened 2023-10-26 04:26 UTC by Mercurial

Basic Implementation of Largest First Coin Selection 

https://cips.cardano.org/cips/cip2/#largestfirst

- ADA only for now 😢
- Working to support MultiAssets

2023-10-26 08:50 UTC, KtorZ requested changes

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +    -> Int
This would be better as a record. As soon as you repeat the same type twice, the signature looses readability as we don't know what is what anymore. A record dispels that nicely.

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +valueToInt value =
```suggestion
lovelace : Value -> Int
lovelace value =
```

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +valueToInt value =
`valueToInt` is implied by the signature already; so we can use the function name to convey additional insights.

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +getValue output =
```suggestion
lovelace : Output -> Int
lovelace output =
```

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +getValue output =
Note: the name is going to clash with the similar function on `Value`, which is why we probably want to move both functions into separate modules `Output` and `Value` to slowly start building a data-centric module structure which is consistent in naming.

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +    List.sum (List.map getValue utxos)
```suggestion
    List.foldr (\value total -> getValue value + total) 0 utxos
```

`List.map` and then `List.sum` traverses the UTxOs list twice. Given that this should work on potentially large UTxO, the cost of traversing twice is important. A fold traverses it once.

I am unsure whether the Elm compiler is capable of performing [fusion](https://wiki.haskell.org/GHC_optimisations#Fusion) (as I believe it requires lazy evaluation to work); so it's better to be explicit about it here.

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +            List.sortWith (\utxo1 utxo2 -> compare (getValue utxo2) (getValue utxo1)) availableUtxo
This can likely be a standalone function. It would be nice if the name also specified the sorting direction (e.g. `sortByDescendingLovelace`).

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +        -- Define a nested recursive function to encapsulate the recurring logic.
```suggestion
```

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +        -- Sort the availableUtxo list once before entering the recursive function.
```suggestion
```

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +        -- Sort the availableUtxo list once before entering the recursive function.
Provide no added insights over the code.

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +        -- Define a nested recursive function to encapsulate the recurring logic.
Provide no added insights over the code.

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +            else if totalValue selected < totalValue requestedOutputs then
This will re-compute the `totalValue` on each iteration loop, which requires to traverse both the select UTxO and the requested outputs which can be arbitrarily large. A suggestion to avoid needless computation:

- Compute the 'totalValue requestOutputs' once before any recursive call
- Decrement the value after each selected UTxO and stop when null or negative.

2023-10-26 08:50 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +                        Err UTxOBalanceInsufficient  -- Error termination when available UTXOs are exhausted.
```suggestion
```suggestion
                case available of
                    [] ->
                        Err UTxOBalanceInsufficient
                
                    Just (utxo :: utxos) ->
                            recursiveSelect utxos (utxo :: selected)
```

2023-10-29 10:46 UTC, mpizenberg commented on src/ElmCardano/CoinSelection.elm
> +    if List.length selected > nmax then
The `List.length` function has a complexity of O(n) where n is the list length. So I'd suggest keeping track of the number of selected utxos in the arguments of the recursive call instead.

2023-10-29 10:52 UTC, mpizenberg commented on src/ElmCardano/CoinSelection.elm
> +    if List.length selected > nmax then
This can be done by adding another argument, or by replacing `nmax` by something like `nmaxLeft` that decreases until reaching 0 where an error is returned.

2023-10-29 16:27 UTC, KtorZ commented on src/ElmCardano/CoinSelection.elm
> +    if List.length selected > nmax then
Ho, I thought that was O(1) in Elm. 🤯

2023-10-30 07:52 UTC, mpizenberg approved these changes
Alright, this looks good to me know.

I've made a few changes. I reordered the arguments of the largestFirst function to have the context be last. In elm we usually put the most relevant data argument last in a function to make pipelines look better.

```elm
buildTheContext
  |> largestFirst maxInputCount
```

I've also done a little bit of renaming so that reading the code is extra clear.

Finally, since the arguments of the recursive functions had many of the same type, I used a record to make sure we don't mix the order. It's an internal function so it doesn't matter for users, but still nicer for maintainers in case there is some refactor needed.

2023-10-30 07:53 UTC, merged

2023-10-30 07:54 UTC, mpizenberg commented
I squashed-merged since the history was getting a bit out-of-hands.